name:
description: >
    Jason Thomas' academic blog. 
about: >
    Hello. My name is Jason Andrew Thomas. I am a PhD student at the University of Washington studying Biomedical and Health Informatics. My focus is in Clinical Informatics surrounding Quality Improvement, Clinical Decision Support, and Data Quality.
    
    Peer-Reviewed Publications:
       
    <span>&#42;</span>These authors contributed equally

    1. Biering-Sørensen T, Kabir M, Waks JW, <b>Thomas J</b>, Post WS, Soliman EZ, Buxton AE, Shah AM, Solomon SD, Tereshchenko LG. Global ECG Measures and Cardiac Structure and Function: The ARIC Study (Atherosclerosis Risk in Communities). Circ Arrhythm Electrophysiol. 2018 Mar;11(3):e005961. doi: 10.1161/CIRCEP.117.005961. PubMed PMID: 29496680; PubMed Central PMCID: PMC5836803.
    
    2. Perez-Alday EA, <b>Thomas JA</b>, Kabir M, Sedaghat G, Rogovoy N, van Dam E, van Dam P, Woodward W, Fuss C, Ferencik M, Tereshchenko LG. Torso geometry reconstruction and body surface electrode localization using three-dimensional photography. J Electrocardiol. 2018 Jan - Feb;51(1):60-67. doi: 10.1016/j.jelectrocard.2017.08.035. Epub 2017 Sep 1. PubMed PMID: 29032808; PubMed Central PMCID: PMC5776048.
    
    3. Kabir MM, Perez-Alday EA, <b>Thomas J</b>, Sedaghat G, Tereshchenko LG. Optimal configuration of adhesive ECG patches suitable for long-term monitoring of a vectorcardiogram. J Electrocardiol. 2017 May - Jun;50(3):342-348. doi: 10.1016/j.jelectrocard.2016.12.005. Epub 2016 Dec 29. PubMed PMID: 28069275; PubMed Central PMCID: PMC5420469.
    
    4. Kabir MM, Sedaghat G, <b>Thomas J</b>, Tereshchenko LG. Reproducibility of Heart Rate Variability Characteristics Measured on Random 10-second ECG using Joint Symbolic Dynamics. Comput Cardiol (2010). 2016 Sep;2016:289-292. doi: 10.23919/CIC.2016.7868736. Epub 2017 Mar 2. PubMed PMID: 28944246; PubMed Central PMCID: PMC5606201.
    
    5. Junell A<span>&#42;</span>, <b>Thomas J<span>&#42;</span></b>, Hawkins L, Sklenar J, Feldman T, Henrikson CA, Tereshchenko LG. Screening entire healthcare system ECG database: Association of deep terminal negativity of P wave in lead V1 and ECG referral with mortality. Int J Cardiol. 2017 Feb 1;228:219-224. doi: 10.1016/j.ijcard.2016.11.128. Epub 2016 Nov 10. PubMed PMID: 27865189; PubMed Central PMCID: PMC5203953.
    
master_repo: false
url: "http://jasonandrewthomas.com"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           
  avatar:         "https://avatars0.githubusercontent.com/u/37385243?s=400&u=6e20465e0093268c616c36a26114063dccf92856&v=4"
  email:          "thomasjt@uw.edu"
  # Social networking links used in footer. Update and remove as you like.
  twitter: https://twitter.com/RealJasonThomas
  github: https://github.com/jatjasonthomas
  linkedin: https://www.linkedin.com/in/jasonandrewthomas/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
